apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-operator
  namespace: openshift-operators
spec:
  channel: stable
  name: strimzi-kafka-operator 
  source: additional-operators 
  sourceNamespace: openshift-operators